using System;
using System.Collections.Generic;

namespace _18AprilDB.Models
{
    public partial class MraFinancialDataNewformat
    {
        public string? StatementId { get; set; }
        public string? CustomerCif { get; set; }
        public string? CustomerName { get; set; }
        public string? StatementDate { get; set; }
        public string? Period { get; set; }
        public string? Audited { get; set; }
        public string? PastOrProjection { get; set; }
        public string? AnnualYtd { get; set; }
        public string? IsQualified { get; set; }
        public string? TurnoverTotalSales { get; set; }
        public string? GrossProfitLoss { get; set; }
        public string? GrossProfitMarginPercent { get; set; }
        public string? NetProfitLoss { get; set; }
        public string? NetProfitMarginPercent { get; set; }
        public string? Otherincome { get; set; }
        public string? TradeDebtorDays { get; set; }
        public string? StockDaysDays { get; set; }
        public string? TradeCreditorDays { get; set; }
        public string? ConversionCycleDays { get; set; }
        public string? TotalAssets { get; set; }
        public string? OfwhichRelatedpartiesduesDrp { get; set; }
        public string? TotalLiabilities { get; set; }
        public string? OfwhichDebt { get; set; }
        public string? Contingencies { get; set; }
        public string? CapitalCommitments { get; set; }
        public string? WorkingCapital { get; set; }
        public string? CurrentRatio { get; set; }
        public string? PaidupCapital { get; set; }
        public string? TangibleNetWorth { get; set; }
        public string? WithdrawnProfits { get; set; }
        public string? Introductionoffunds { get; set; }
        public string? Leverage { get; set; }
        public string? AdjustedLeverage { get; set; }
        public string? NetDebtinclcontingenciestoEquity { get; set; }
        public string? FinancialCurrency { get; set; }
        public string? DisplayUnit { get; set; }
        public string? PlNetRevenue { get; set; }
        public string? PlGrossProfit { get; set; }
        public string? PlSellingGen { get; set; }
        public string? PlEbitda { get; set; }
        public string? PlDepreciation { get; set; }
        public string? PlFinCharges { get; set; }
        public string? PlNonOp { get; set; }
        public string? PlPbt { get; set; }
        public string? PlPat { get; set; }
        public string? PlDividendWithdrawal { get; set; }
        public string? PlNetCash { get; set; }
        public string? BsWcStDebit { get; set; }
        public string? BsCpltd { get; set; }
        public string? BsDebt { get; set; }
        public string? BsTotalExtDebt { get; set; }
        public string? BsLoansFromPromoters { get; set; }
        public string? BsEquity { get; set; }
        public string? BsTotalOut { get; set; }
        public string? BsPaidupCapital { get; set; }
        public string? BsTangibleNet { get; set; }
        public string? BsInvIn { get; set; }
        public string? BsAdjTnw { get; set; }
        public string? BsTotalCurrAssets { get; set; }
        public string? BsCashBalances { get; set; }
        public string? BsOtherCur { get; set; }
        public string? BsTotalCurrLiab { get; set; }
        public string? BsNetWorkingCapital { get; set; }
        public string? BsNetFixedAssets { get; set; }
        public string? BsContingentLi { get; set; }
        public string? KrSgaExp { get; set; }
        public string? KrGrossMargin { get; set; }
        public string? KrEbitda { get; set; }
        public string? KrFinCharges { get; set; }
        public string? KrPatMargin { get; set; }
        public string? KrEbitdaInt { get; set; }
        public string? KrTotalDebit { get; set; }
        public string? KrTolTnw { get; set; }
        public string? KrTolAtnw { get; set; }
        public string? KrTotalDebitAtnw { get; set; }
        public string? KrTermDebit { get; set; }
        public string? KrTotalDebitTnw { get; set; }
        public string? KrCrRatio { get; set; }
        public string? KrRoce { get; set; }
        public string? KrDscr { get; set; }
        public string? KrFxdassetratio { get; set; }
        public string? KrTargetted { get; set; }
        public string? KrSustGrowth { get; set; }
        public string? KrActProj { get; set; }
        public string? KrDiviPayout { get; set; }
        public string? KrAssetSales { get; set; }
        public string? KrAdjPatMargin { get; set; }
        public string? HlRawMat { get; set; }
        public string? HlWorkProg { get; set; }
        public string? HlFinGoods { get; set; }
        public string? HlSundryDebt { get; set; }
        public string? HlTotalInv { get; set; }
        public string? HlTradeCred { get; set; }
        public string? HlTotalOper { get; set; }
        public string? CfNetCash { get; set; }
        public string? CfWrkgCap { get; set; }
        public string? CfDebtors { get; set; }
        public string? CfInventory { get; set; }
        public string? CfIncCreditors { get; set; }
        public string? CfOtherAssetsLoans { get; set; }
        public string? CfShortDebt { get; set; }
        public string? CfMaintCap { get; set; }
        public string? CfSchDebtRepay { get; set; }
        public string? CfOthPrPmt { get; set; }
        public string? CfFreeCash { get; set; }
        public string? CfGrCapex { get; set; }
        public string? CfDividPai { get; set; }
        public string? CfCashDisc { get; set; }
        public string? CfNetIssuePmt { get; set; }
        public string? CfEqShares { get; set; }
        public string? CfPrefShares { get; set; }
        public string? CfOthSource { get; set; }
        public string? CfOthCash { get; set; }
    }
}
