using System;
using System.Collections.Generic;

namespace _18AprilDB.Models
{
    public partial class TblExposuresuploadSourceSystemFxdBkp
    {
        public string? TradeId { get; set; }
        public string? ExternalReference { get; set; }
        public string? TradeKeyword3Externalreferenceid { get; set; }
        public string? TradeKeyword4Opicsid { get; set; }
        public string? InternalDeal { get; set; }
        public string? CounterpartyAttributeCifId { get; set; }
        public string? Tradestatus { get; set; }
        public string? Book { get; set; }
        public string? ProductDescription { get; set; }
        public string? ProductFamily { get; set; }
        public string? ProductType { get; set; }
        public string? TradeKeyword2FxProductcodes { get; set; }
        public string? TradeKeyword2MerchantProductcodes { get; set; }
        public string? TradeKeyword2FxTradetype { get; set; }
        public string? TradeKeyword2Fxswapfarleg { get; set; }
        public string? TradeKeyword2Fxswapnearleg { get; set; }
        public string? BundleName { get; set; }
        public string? Trader { get; set; }
        public string? CounterpartyId { get; set; }
        public string? Counterparty { get; set; }
        public string? CounterpartyCountry { get; set; }
        public string? CounterpartyFinancial { get; set; }
        public string? TradeDate { get; set; }
        public string? MaturityDate { get; set; }
        public string? ExpiryDate { get; set; }
        public string? TradeCurrency { get; set; }
        public string? OutstandingNotional { get; set; }
        public string? Notional { get; set; }
        public string? NotionalBase { get; set; }
        public string? RcvLegOutstandingCcy { get; set; }
        public string? RcvLegOutstandingNotional { get; set; }
        public string? RcvLegPrincipal { get; set; }
        public string? PayLegOutstandingCcy { get; set; }
        public string? PayLegOutstandingNotional { get; set; }
        public string? PayLegPrincipal { get; set; }
        public string? BuySell { get; set; }
        public string? PutCall { get; set; }
        public string? PrincipalAmount { get; set; }
        public string? CaNotional { get; set; }
        public string? CaNotionalBase { get; set; }
        public string? CurNotionalPay { get; set; }
        public string? CurNotionalPayBase { get; set; }
        public string? CurNotionalRec { get; set; }
        public string? CurNotionalRecBase { get; set; }
        public string? PrimAmt { get; set; }
        public string? PrimCur { get; set; }
        public string? SecAmt { get; set; }
        public string? SecCur { get; set; }
        public string? Amort { get; set; }
        public string? RateIndex { get; set; }
        public string? PayLegFixedRate { get; set; }
        public string? PayLegFloatingRate { get; set; }
        public string? PayLegRateIndexSpread { get; set; }
        public string? PayLegResetFrequency { get; set; }
        public string? PayLegPaymentFrequency { get; set; }
        public string? PayLegIndexFrequency { get; set; }
        public string? RcvLegFixedRate { get; set; }
        public string? RcvLegFloatingRate { get; set; }
        public string? RcvLegRateIndexSpread { get; set; }
        public string? RcvLegResetFrequency { get; set; }
        public string? RcvLegPaymentFrequency { get; set; }
        public string? RcvLegIndexFrequency { get; set; }
        public string? Strike { get; set; }
        public string? TradePrice { get; set; }
        public string? DetailedDataBase { get; set; }
        public string? NpvPricinganalysisCadFxoMtm { get; set; }
        public string? NpvBasePricinganalysisCadFxoMtm { get; set; }
        public string? NpvPricinganalysisPricingSummary { get; set; }
        public string? NpvBasePricinganalysisPricingSummary { get; set; }
        public string? NpvPayleg { get; set; }
        public string? NpvPaylegBase { get; set; }
        public string? NpvRecleg { get; set; }
        public string? NpvReclegBase { get; set; }
        public string? Accrual { get; set; }
        public string? AccrualBase { get; set; }
        public string? AccrualPayleg { get; set; }
        public string? AccrualPaylegBase { get; set; }
        public string? AccrualRecleg { get; set; }
        public string? AccrualReclegBase { get; set; }
        public string? DurationBase { get; set; }
        public string? Pv01 { get; set; }
        public string? Pv01Base { get; set; }
        public string? Delta01 { get; set; }
        public string? Delta01Base { get; set; }
        public string? Delta { get; set; }
        public string? DeltaBase { get; set; }
        public string? Gamma { get; set; }
        public string? GammaBase { get; set; }
        public string? Rho { get; set; }
        public string? RhoBase { get; set; }
        public string? Rho2 { get; set; }
        public string? Rho2Base { get; set; }
        public string? Theta { get; set; }
        public string? ThetaBase { get; set; }
        public string? Vega { get; set; }
        public string? VegaBase { get; set; }
        public string? CurrentNotional { get; set; }
        public string? CurrentNotionalBase { get; set; }
        public string? Pay { get; set; }
        public string? Receive { get; set; }
        public string? FinalPrice { get; set; }
        public string? FixedRate { get; set; }
        public string? FxFarAllinRate { get; set; }
        public string? FxFarPrimAmount { get; set; }
        public string? FxFarSecAmount { get; set; }
        public string? FxNearAllinRate { get; set; }
        public string? FxSpotRate { get; set; }
        public string? PrimaryOutstanding { get; set; }
        public string? SecondaryOutstanding { get; set; }
        public string? TradeKeyword2Tradetype { get; set; }
        public DateTime? LoadDate { get; set; }
    }
}
